version: 2

models:
  - name: dim_film
    columns:
      - name: film_id
        tests: ['unique', 'not_null']
  - name: dim_customer
    columns:
      - name: customer_id
        tests: ['unique', 'not_null']
  - name: fct_rental
    columns:
      - name: rental_id
        tests: ['unique', 'not_null']
  - name: dim_store
    columns: 
      - name: store_id
        tests: ['unique', 'not_null']
  - name: dim_address
    columns: 
      - name: address_id
        tests: ['unique', 'not_null']
