dw:
  target: dev
  outputs:
    dev:
      account: "{{ env_var('SNOWFLAKE_ACCOUNT_ID') }}"
      database: AIRBYTE_DATABASE
      password: "{{ env_var('AIRBYTE_PASSWORD') }}"
      role: AIRBYTE_ROLE
      schema: AIRBYTE_SCHEMA
      threads: 12
      type: snowflake
      user: AIRBYTE_USER
      warehouse: AIRBYTE_WAREHOUSE
